### ISSUE TITLE
Separate containers for third-party services

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [drewag/Decree#1]
A small suggestion. Maybe you could consider extracting the third-party services out to separate containers? To keep the main library from bloating. Like [Eureka](https://github.com/xmartlabs/Eureka) did with their [custom rows catalog](https://github.com/EurekaCommunity). 

Because currently, if you were to add the source files manually, you get compile errors in those third-party files. So users who don't need them have to remove those files and bits and pieces of code from here and there to get it working.

**Comment by drewag** [comment]
Are you saying that you are currently getting compiler errors or are you referring to the Eureka project?

Thanks for the suggestion. I did consider separating out the services, but they are extremely lightweight. If anything is worth separating out, it would be the input and output formats, but I still don't think they're big enough to be worth the complication at this point.

**Comment by drewag** [comment]
Actually, I guess I didn't consider separating out all the services into one other repository. That may be worth it. I'll think about it a bit more.

**Comment by Isuru-Nanayakkara** [comment]
> Are you saying that you are currently getting compiler errors or are you referring to the Eureka project?
> 
> Thanks for the suggestion. I did consider separating out the services, but they are extremely lightweight. If anything is worth separating out, it would be the input and output formats, but I still don't think they're big enough to be worth the complication at this point.

Oh no, I was referring to Decree. But never mind the compile time errors. It was due to my Xcode acting up. Cleaning the project resolved that.

I was thinking like, if an external library like CryptoSwift is there only to work with AWS, it might be better off as a separate entity because it adds an extra dependency to the overall library.

**Comment by drewag** [comment]
Ya, removing the CryptoSwift dependency would indeed be a win. It might come back for more advanced Auth types, but perhaps not.

**Comment by drewag** [comment]
Ok, thanks for the suggestion. I did end up separating the repositories. This one no longer has any of the services (nor the dependency on CryptoSwift) and I created the separate repository [DecreeServices](https://github.com/drewag/DecreeServices) which also supports CocoaPods.

**Comment by Isuru-Nanayakkara** [comment]
Awesome!
