### ISSUE TITLE
Setting custom headers for certain endpoints only

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [drewag/Decree#3]
I already explained the context of my API elsewhere but I'll do a gist here for completion sake.

I have 3 endpoints named login, verify and profile. I don't need to pass any additional custom headers for the first two. For the third one (then all subsequent requests from there on out), I have to set a custom header. So I've set the `authorizationRequirement` property like this for all 3.

```swift
struct Login: InOutEndpoint {
    typealias Service = MyAPI
    static let authorizationRequirement = AuthorizationRequirement.none
    
    // ...
}

struct Verify: InOutEndpoint {
    typealias Service = MyAPI
    static let authorizationRequirement = AuthorizationRequirement.none
    
    let path: String = "/login/DRI/verify/"
    
    // ..
}

struct GetProfile: OutEndpoint {
    typealias Service = MyAPI
    static let authorizationRequirement = AuthorizationRequirement.required
}
```

In the `WebService` implementation, I've set the `authorization` property like this.

```swift
struct MyAPI: WebService {
    static var shared = MyAPI()
    
    let baseURL = URL(string: "http://example.com/api")!
    var authorization = Authorization.custom(key: "token", value: SessionManager.shared.token)
    
    // ..
}
```

`SessionManager` is a class where I store the token.

I ran into a bit of a snag when I set the custom header. Let me elaborate. After calling `Login()` endpoint, I call `Verify()`. This is where I get the value for the custom header. I save the token value in the `SessionManager`.

```swift
Verify().makeRequest(with: .init(phoneno: phoneNumber, code: otp)) { result in
    switch result {
    case .success(let output):
        SessionManager.shared.token = output.data.token
    case .failure(let error):
        print("Failed to verify: \(error)")
    }
}
```

I then call `Profile()` endpoint and noticed that the request fails for not having a value for the custom header. I assume that `MyAPI` (`WebService implementation`) is only initialized once so the newly assigned value to `SessionManager.shared.token` above isn't getting applied to the custom header when I call the next request.

So I assigned the token to the custom header directly like so.

```swift
Verify().makeRequest(with: .init(phoneno: phoneNumber, code: otp)) { result in
    switch result {
    case .success(let output):
        MyAPI.shared.authorization = Authorization.custom(key: "token", value: output.data.token)
    case .failure(let error):
        print("Failed to verify: \(error)")
    }
}
```

This fixes the issue. However it just looks....off. Because I'm already setting `var authorization = Authorization.custom(key: "token", value: SessionManager.shared.token)` in the web service implementation with no effect so I have to set it from "outside".

Is this the correct way of doing this? I remember you mentioning about considering a way to add headers directly to the endpoints themselves. Which I also think is a better approach since you have more control over it. Did you decide against it or is it still on the table?

**Comment by drewag** [comment]
Yes, this is largely how I would expect you to implement it. The alternative is for you to make the authorization a calculated property:

```swift
struct MyAPI: WebService {    
    var authorization: Authorization {
        guard let token = SessionManager.shared.token else {
            return .none
        }
        return .custom(key: "token", value: token)
    }
    
    // ..
}
```

For me, it depends on if there are other things the Session manager is doing. If all it is doing is storing the token, I would just set it directly on `MyApi`.

I am still planning to add some sort of individual endpoint custom header support, but auth/sessions is still such a common use case that I wanted it to have its own built-in support. Especially around the idea of endpoints requiring auth.

I'd be curious how you would implement it more effectively with custom headers on the endpoint itself. I'm also certainly open to you implementing custom headers yourself and submitting a pull-request ;) (I'd be happy to discuss a plan of action before you start).

**Comment by Isuru-Nanayakkara** [comment]
Thanks! Currently `SessionManager` is indeed only storing the token.

 I don't know if I'm knowledgable enough to alter your 'baby' haha 😬 But I will certainly give it a try. I was thinking along the lines of adding a property to the `Endpoint` protocol to add any additional headers. So it could be used for other headers as well, not just authentication. 

Just give me a bit of time :) Kinda pressed for time with a project I'm doing atm.

**Comment by Isuru-Nanayakkara** [comment]
I'm getting the **Cannot assign to property: 'authorization' is a get-only property** error when assigning the value to `MyAPI.shared.authorization` after changing the property to a calculated one.

**Comment by drewag** [comment]
Those are two different options:
1. Calculated property based on the SessionManager where you set the token on the session manager and the new value is automatically picked up on the next request because it is a calculated property.
2. Variable property where you set it directly on the service

Also, your pull request would go through code review (by me) so I'm not worried and I would love to have another contributor! That was also my thought for adding custom headers. A `headers` instance property of type `[(String,String)]` but I haven't gotten an opportunity to think through how it might integrate with the idea of input and if there is any benefit to using Coding instead of simple keys and values.

**Comment by Isuru-Nanayakkara** [comment]
I'm getting the **Cannot assign to property: 'authorization' is a get-only property** error when assigning the value to `MyAPI.shared.authorization` after changing the property to a calculated one. 

I managed to fix it by adding explicit getter and setter like so. 

```swift
var authorization: Authorization {
    get {
        guard let token = SessionManager.shared.token else {
            return .none
        }
        return .custom(key: "token", value: token)
    }
    set {
        authorization = newValue
    }
}
```

Although I'm getting a warning **All paths through this function will call itself** for the setter. Would that be an issue?

**Comment by drewag** [comment]
Yes, that's going to indeed be a problem (you will get an infinite loop when setting it). See my previous comment about my actual recommendation. But to go the setter route, you would do:

```swift
set {
    switch newValue {
    case .custom(_, let token):
        SessionManager.shared.token = token
    default:
        SessionManager.shared.token = nil    
    }
}
```
